name: Docker Build

on:
  push:
    branches: [ "dev", "staging", "main", "feature/*" ]
  pull_request:
    branches: [ "dev", "staging", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # 拉取仓库代码到 CI 环境

    - name: Set up Docker Buildx  # 初始化 Docker 构建工具
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image  # 构建镜像（基于仓库根目录的 Dockerfile）
      run: |
        docker build -t my-app:${{ github.sha }} .  # 用 Git 提交哈希作为标签，确保唯一性
        
    - name: Verify image  # 可选步骤：验证镜像是否构建成功
      run: |
        docker images | grep my-app  # 检查镜像是否存在
