name: Python Tests
# 触发条件：feature/* 分支推送 + 向 dev/staging/main 提 PR
on:
  workflow_dispatch:
  push:
    branches: [ 'feature/**' ]
  pull_request:
    branches: [ dev, staging, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：拉取代码
      - uses: actions/checkout@v4
      
      # 步骤2：设置 Python 3.12（匹配 Dockerfile 版本）
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'  # 缓存依赖，加速构建
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # 升级pip
          pip install -r requirements.txt      # 安装requirements.txt中的依赖
          
      # 步骤3：安装依赖（文档指定 pytest==8.3.3）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

       # 新增：代码linting
      - name: Lint code with flake8
        run: |
          # 1. 检查严重错误，发现即终止 CI
          flake8 app/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # 2. 检查代码规范，不终止但输出统计
          flake8 app/ tests/ --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      # 步骤4：运行测试（指定 tests/ 目录下的测试文件）
      - name: Run tests
        run: pytest tests/test_app.py -v
